nvidia-apply-extra.c
While trying to create a flatpak manifest for nvidia enabled version of [zenith](https://github.com/bvaisvil/zenith), the libnvidia-ml.so symlink is missing.
=> Add libnvidia-ml.so symlink

nvidia-apply-extra.c
Closes #44 
---
I checked multiple installers and determined that no drivers before the 400 series included the OptiX library.
Specifically for Blender, the [official wiki](https://wiki.blender.org/wiki/Reference/Release_Notes/2.81/Cycles) states `Linux: driver version 435.12 or newer` (even though this driver doesn't appear to have been released publicly; 435.17 is the closet).
=> Add libnvoptix.so symlink

nvidia-apply-extra.c
The implicit Vulkan layer "nvidia_layers.json", provided by the Nvidia
drivers, is a requirement for Optimus.
Helps:
https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/issues/35
---
In order to make this implicit layer available in a container, we also need this patch for the freedesktop runtime https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/4723
=> Include implicit Vulkan layer nvidia_layers.json

nvidia-apply-extra.c
Closes #68
All versions of the driver support frame buffer capture.
=> Add libnvidia-fbc.so.1 symlink

nvidia-apply-extra.c
This soversion-less library appears to be required for Vulkan on Wayland:
```
135:	file=libnvidia-vulkan-producer.so [0];  dynamically loaded by /usr/lib/x86_64-linux-gnu/GL/nvidia-495-44/lib/libnvidia-glcore.so.495.44 [0]
```
After its addition, `org.freedesktop.Platform.VulkanInfo//21.08` should start to work.
Another piece towards solving #76
=> Create `libnvidia-vulkan-producer.so` symlink

nvidia-apply-extra.c, org.freedesktop.Platform.GL.nvidia.json.in
`ldconfig` is a statically linked program, so we can copy it from the SDK at build time and use at install time without any dependencies.
Letting `ldconfig` create library symlinks for us makes the `apply_extra` significantly simpler and more future-proof: in case of new libraries added, we won't always need to update `apply_extra`.
=> Use `ldconfig` to create library symlinks

nvidia-Makefile, nvidia-apply-extra.c
Profiles are installed to `extra/share/nvidia/`, with a relative symlink targeting this dir at `share/nvidia`.
This will require some relevant changes on the runtime (or app) side to be useful, but we need the profiles to be shipped with GL extension in the first place anyway.
Fixes #66
=> Install application profiles

data/nvidia-520.61.05-i386.data, data/nvidia-520.61.05-x86_64.data
#134 was missing a size and the hash was incorrect.
=> Fix Tesla 520.61.05 hash and size

nvidia-Makefile, nvidia-apply-extra.c, org.freedesktop.Platform.GL.nvidia.json.in
Starting from beta release 530.30.02, NVIDIA began compressing their drivers using zstd instead of xz.
From the [release notes](https://www.nvidia.com/Download/driverResults.aspx/199985/en-us/):
>Changed the compression format of the .run installer package from xz to zstd. This results in a smaller compressed package, and faster decompression performance. A fallback zstd decompressor is embedded into the installer package for systems which do not already have a zstd decompression program installed.
Fixes #160
=> Support extracting zstd-compressed drivers

data/nvidia-545.23.08-aarch64.data, data/nvidia-545.23.08-i386.data, data/nvidia-545.23.08-x86_64.data
It looks like something is broken with PR #214, which should have automatically downloaded the CUDA `.run` file, then extracted it to find the actual NVIDIA driver `.run` file to install, but instead it results in #224.
I'm not exactly sure what the issue is, but if we self-host the NVIDIA driver `.run` file, the old existing process should work just as well!
These files are hosted at https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/releases/tag/cuda, which seems okay under both NVIDIA's and GitHub's rules (see https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/issues/224#issuecomment-1893017543).
This will only be required until we switch to using a normal package, and not extra-data (see https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/pull/167). …
=> Fix CUDA 545.23.08 drivers

Makefile
To improve a bit the experience when packaging locally.
These are the default arguments currently used by Flathub's buildbot.
=> Makefile: Set default options for `flatpak-builder`

nvidia-apply-extra.c
From the release notes of [beta driver 319.12](https://www.nvidia.com/Download/driverResults.aspx/60198/en-us/):
>Added support for application profiles to the NVIDIA client-side GLX implementation. See the "Application Profiles" chapter of the README for more information.
=> Only install application profiles on 319xx and newer

nvidia-apply-extra.c
New rules for symlinking this library:
- Library is only present on versions 470xx through 535xx.
There are two exceptions to this, however:
Versions [470.42.01](https://www.nvidia.com/Download/driverResults.aspx/176525/en-us/) and [470.57.02](https://www.nvidia.com/Download/driverResults.aspx/177145/en-us/) don't include it, for some reason.
- There's no 32-bit counterpart for this library.
=> Fix symlinking rules for `libnvidia-vulkan-producer.so`

nvidia-apply-extra.c
And also ensure that the resulting symlink points to an existing file.
=> Ensure symlink creation is successful

org.freedesktop.Platform.GL.nvidia.json.in
This reverts commit https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/commit/b1d0cafed1172544fa7ff4049a0ff12657a3de00.
After moving to CMake, libarchive began failing to build on i386. See https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/issues/283#issuecomment-2307481607 for more details on the error.
I also took this opportunity to add new build flags that disable unused components of libarchive, which should slightly speed up the build process:
- `--disable-bsdunzip`: Disable build of bsdunzip
- `--without-libb2`: Don't build support for BLAKE2 through libb2
- `--without-cng`: Don't build support of CNG(Crypto Next Generation)
- `--without-mbedtls`: Build without crypto support from mbed TLS
Closes #283
=> Go back to Autotools for building libarchive

org.freedesktop.Platform.GL.nvidia.json.in
The cleaning up is already [covered by](https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/blob/4b830af0570b68f9a744d20ebd67eb437df0a658/nvidia-Makefile#L7) `nvidia-Makefile`.
This change stops `flatpak-builder` from inadvertently removing the `lib` -> `extra` symlink at the "clean up stage", which was preventing apps from locating driver libraries.
Fixes #288
=> libzstd: Don't clean up files

README.md, org.freedesktop.Platform.GL.nvidia.json.in
Changes:
- `libarchive`: update to [3.7.5](https://github.com/libarchive/libarchive/releases/tag/v3.7.5)
- `libzstd`: update to [1.5.6](https://github.com/facebook/zstd/releases/tag/v1.5.6)
There’s also a change where `libarchive` is configured with `--disable-dependency-tracking`, which, on my old 2013 quad-core machine, yields a decrease of ~4.6 seconds in overall build time.
These changes were tested locally, by building and installing the 560.35.03 driver for `x86_64` and `i386`.
=> Update dependencies used by the driver extractor

nvidia-apply-extra.c
This library was introduced with the 525xx series:
>The NVAPI library (`/usr/lib/libnvidia-api.so.1;`); NVAPI provides an interface for managing properties of GPUs. The NVAPI library provides runtime support for NVAPI applications.
Source: https://download.nvidia.com/XFree86/Linux-x86_64/525.53/README/installedcomponents.html
Fixes #318
=> Install unversioned `libnvidia-api.so.1` library

README.md, build.sh, flathub.json, org.freedesktop.Platform.GL.nvidia.json.in
This allows us to stop depending on the ancient 1.6 i386 SDK to package the i386 driver.
With these changes, the i386 driver is now packaged on a x86_64 host.
Unfortunately, we now also have to include zlib and liblzma, because the 24.08 SDK doesn't include static libraries (.a files) for them, and that will likely increase the overall build time.
---
I've tested the installation process on the following driver versions (x86_64 only):
- 367.57 (the oldest version we currently have)
- 470.256.02 (the latest driver supported by my GPU)
- 565.77 (the newest version we currently have)
I have not tested on aarch64, but I don't see why it would cause problems...
All changes are in a single commit on purpose, so we can easily revert it in case things go bad.
=> Package the i386 driver on x86_64

build.sh, nvidia-apply-extra.c, org.freedesktop.Platform.GL.nvidia.json.in
On PR #322, I forgot to update some places to make the driver extractor program (`nvidia-apply-extra.c`) properly extract the 32-bit driver files when installing the GL32 extension, as opposed to the x86_64 ones... This PR addresses that problem.
=> Fixup: Package the i386 driver on x86_64

org.freedesktop.Platform.GL.nvidia.json.in
This base extension contains pre-built static libraries for zlib, liblzma, libzstd and libarchive, meaning we don't have to download and compile these libraries for every version we package.
The speed gain is massive: Without this extension, packaging 5 different driver versions on my personal computer (quad-core CPU @ 3.6 GHz) took a whopping 6 minutes.
With the base extension, the same packaging process took only 23 seconds, almost 16 times faster!
---
Marking as draft for now, though, because I intend to merge this when NVIDIA releases their next driver - just to avoid releasing multiple updates needlessly [and annoying users](https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/issues/42).
Collaborators, feel free to review or question these changes in the meantime.
=> Use base extension with pre-built static libraries

data/nvidia-570.86.10-aarch64.data, data/nvidia-570.86.10-i386.data, data/nvidia-570.86.10-x86_64.data, nvidia-apply-extra.c, versions.sh
As usual, these installers were manually extracted by me from the ~5 GB CUDA 12.8.0 installers, for x86_64 and aarch64. I then uploaded the extracted installers to GitHub's [releases page](https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/releases/tag/cuda).
R570 is a new major version not previously packaged here, but as far as I could tell, the only difference between this version and R565 is the introduction of a new DLL called `nvngx_dlssg.dll`, which should be already covered by the driver extractor [here](https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/blob/ece22284e21d10b53c4f70b1d33ec83b7b75af72/nvidia-apply-extra.c#L219-L224).
---
This PR also includes an unrelated commit that fixes #330.
=> Add CUDA 570.86.10

nvidia-apply-extra.c
From the release notes of version [535.43.02](https://www.nvidia.com/en-us/drivers/details/205039/):
> Added `nvoptix.bin` to the driver package. This data file is used by the OptiX ray tracing engine library, `libnvoptix.so.1`.
[The documentation](https://us.download.nvidia.com/XFree86/Linux-x86_64/535.43.02/README/installedcomponents.html#:~:text=OptiX%20also%20includes%20a%20data%20file%20/usr/share/nvidia/nvoptix.bin.) tells us to install this file to `share/nvidia`.
Fixes #184
=> Install nvoptix.bin

data/nvidia-570.86.16-aarch64.data
The aarch64 data was missing in PR #336
=> Add Beta 570.86.16 (aarch64)

nvidia-apply-extra.c
By not installing the Vulkan and EGL ICDs in the GL32 extension, we ended up breaking 32-bit Vulkan support for most applications that need it, e.g. game launchers that run 32-bit Windows games via Wine + DXVK.
The breakage was not noticed by me when I introduced this change, because my tests were only done using Flatpak'd Steam, which unluckily for me, includes a workaround that prevents the breakage.
The workaround is simple and consists of adding the path of the Vulkan ICD to the [`XDG_CONFIG_DIRS`](https://vulkan.lunarg.com/doc/view/1.3.250.1/windows/LoaderDriverInterface.html#driver-discovery-on-linux) environment variable, thus allowing the Vulkan Loader (`libvulkan.so`) to find it.
Another breakage affected applications using the EGL API (e.g. Wine with its native Wayland driver), …
=> Revert "Extract just library files when on GL32"

data/nvidia-575.51.03-aarch64.data, data/nvidia-575.51.03-i386.data, data/nvidia-575.51.03-x86_64.data, versions.sh
As usual, these installers were manually extracted by me from the 5 GB CUDA 12.9.0 installers, for x86_64 and aarch64. I then uploaded the extracted installers to [our releases page](https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/releases/tag/cuda).
=> Add CUDA 575.51.03

nvidia-extractor/nvidia-extract.c
This is one of those libraries that aren't versioned after the driver version (like most libraries are), so we have to manually mark it for extraction.
This library was introduced in [beta driver 575.51.02](https://www.nvidia.com/en-us/drivers/details/243334/).
=> Add custom-versioned `libnvidia-nvvm70`

setup-matrix.py
We keep running out of disk space while exporting the drivers: https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/actions/runs/17412754189/job/49435186818#step:6:5294
I first tried to work around this in #378, but that wasn't enough, so let's try to reduce the build batches from 30 to 15 and see how it goes.
My guess is that this is happening now because the forked version of `flatpak-builder` we use to build the drivers [was recently modified](https://github.com/flathub-infra/flatpak-builder/commit/9d54e13a6c042558ff2265f279d60e358f86246b) to always export a `.Sources` package(?) for x86_64 builds, which seems to require about twice as much disk space as before...
=> CI: Reduce build batches from 30 to 15
